<a href="https://colab.research.google.com/github/mukiskaijeaw/GO-analysis-in-R/blob/main/prac_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = {
    "month" : ["Jan", "Feb", "Mar"],
    "sales" : [1000, 1500, 2000]
}
df = pd.DataFrame(data)
print(df)

  month  sales
0   Jan   1000
1   Feb   1500
2   Mar   2000

In [3]:
df.head(1)

  month  sales
0   Jan   1000

In [4]:
df.tail(1)

  month  sales
2   Mar   2000

In [5]:
df.info(1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   month   3 non-null      object
 1   sales   3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [6]:
df.shape

(3, 2)

In [7]:
df.describe()

        sales
count     3.0
mean   1500.0
std     500.0
min    1000.0
25%    1250.0
50%    1500.0
75%    1750.0
max    2000.0

In [9]:
df['sales']

0    1000
1    1500
2    2000
Name: sales, dtype: int64

In [10]:
df['sales_vat'] = df['sales']*1.07

In [11]:
df

  month  sales  sales_vat
0   Jan   1000     1070.0
1   Feb   1500     1605.0
2   Mar   2000     2140.0

In [13]:
df[df.sales>1000]

  month  sales  sales_vat
1   Feb   1500     1605.0
2   Mar   2000     2140.0

In [14]:
df['sales'].sum()

np.int64(4500)

In [15]:
df['sales'].mean()

np.float64(1500.0)

In [16]:
df['sales'].max()

2000

In [17]:
df.describe()

        sales  sales_vat
count     3.0        3.0
mean   1500.0     1605.0
std     500.0      535.0
min    1000.0     1070.0
25%    1250.0     1337.5
50%    1500.0     1605.0
75%    1750.0     1872.5
max    2000.0     2140.0